/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package qlvembay;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author khanh ngu
 */
public class TTKH extends javax.swing.JInternalFrame {

    /**
     * Creates new form TTKH
     */
    public TTKH() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    private Connection getConnect() {
        try {
        // Thay đổi thông tin kết nối theo cấu hình của bạn
        String url = "jdbc:mysql://127.0.0.1:3306/qlvemaybay";
        String user = "root";
        String password = "";

        // Tạo kết nối
        Connection connection = DriverManager.getConnection(url, user, password);

        System.out.println("Kết nối thành công đến cơ sở dữ liệu!");
        return connection;
    } catch (SQLException ex) {
        System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
        return null;
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbkhachhang = new javax.swing.JTable();
        btnLuukh = new javax.swing.JButton();
        btnAddkh = new javax.swing.JButton();
        btnSuakh = new javax.swing.JButton();
        btnXoakh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Mã khách hàng:");

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Ngày sinh:");

        txtNgaySinh.setText("\n");
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa chỉ:");

        jLabel4.setText("CCCD:");

        jLabel5.setText("Giới tính:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        cboGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGioiTinhActionPerformed(evt);
            }
        });

        jLabel14.setText("Điện thoại:");

        txtQuocTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuocTichActionPerformed(evt);
            }
        });

        jLabel6.setText("Quốc tịch:");

        tbkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ và tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Quốc tịch", "CCCD", "Điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbkhachhang);

        btnLuukh.setText("Lưu");
        btnLuukh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuukhActionPerformed(evt);
            }
        });

        btnAddkh.setText("Thêm");
        btnAddkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddkhActionPerformed(evt);
            }
        });

        btnSuakh.setText("Sửa");
        btnSuakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuakhActionPerformed(evt);
            }
        });

        btnXoakh.setText("Xóa");
        btnXoakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoakhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnLuukh)
                        .addGap(98, 98, 98)
                        .addComponent(btnAddkh)
                        .addGap(117, 117, 117)
                        .addComponent(btnSuakh)
                        .addGap(101, 101, 101)
                        .addComponent(btnXoakh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtCCCD)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddkh)
                    .addComponent(btnSuakh)
                    .addComponent(btnXoakh)
                    .addComponent(btnLuukh))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuakhActionPerformed
        int selectedRowIndex = tbkhachhang.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Get the values from the selected row
            String idkh = tbkhachhang.getValueAt(selectedRowIndex, 0).toString();
            String tenkh = tbkhachhang.getValueAt(selectedRowIndex, 1).toString();
            String ngaysinhkh = tbkhachhang.getValueAt(selectedRowIndex, 2).toString();
            String gioitinhkh = tbkhachhang.getValueAt(selectedRowIndex, 3).toString();
            String diachi = tbkhachhang.getValueAt(selectedRowIndex, 4).toString();
            String quoctich = tbkhachhang.getValueAt(selectedRowIndex, 5).toString();
            String cccd = tbkhachhang.getValueAt(selectedRowIndex, 6).toString();
            String sdt = tbkhachhang.getValueAt(selectedRowIndex, 7).toString();

            // Fill the input fields with the selected data
            txtMaKhachHang.setText(idkh);
            txtHoTen.setText(tenkh);
            cboGioiTinh.setSelectedItem(gioitinhkh);
            txtNgaySinh.setText(ngaysinhkh);
            txtCCCD.setText(cccd);
            txtDiaChi.setText(diachi);
            txtDienThoai.setText(sdt);
            txtQuocTich.setText(quoctich);
        } else {
            System.out.println("Vui lòng chọn một dòng để sửa!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuakhActionPerformed

    private void btnAddkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddkhActionPerformed
        try (Connection connection = getConnect()) {
            // Kiểm tra nếu kết nối thành công
            if (connection != null) {
                // Lấy thông tin từ giao diện người dùng
                String idkh = txtMaKhachHang.getText();
                String tenkh = txtHoTen.getText();
                String gioitinhkh = (String) cboGioiTinh.getSelectedItem();
                String ngaysinhkh = txtNgaySinh.getText();
                String cccd = txtCCCD.getText();
                String diachi = txtDiaChi.getText();
                String sdt = txtDienThoai.getText();
                String quoctich = txtQuocTich.getText();

                // Chuẩn bị câu truy vấn SQL để thêm khách hàng
                String query = "INSERT INTO khach_hang (id, ten, Ngaysinh, gioi_tinh, dia_chi, quoc_tich, CCCD, dien_thoai) VALUES (?,?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                    // Thiết lập giá trị cho các tham số trong câu truy vấn
                    preparedStatement.setString(1, idkh);
                    preparedStatement.setString(2, tenkh);
                    preparedStatement.setString(3, ngaysinhkh);
                    preparedStatement.setString(4, gioitinhkh);
                    preparedStatement.setString(5, diachi);
                    preparedStatement.setString(6, quoctich);
                    preparedStatement.setString(7, cccd);
                    preparedStatement.setString(8, sdt);

                    // Thực hiện truy vấn thêm
                    int rowsAffected = preparedStatement.executeUpdate();

                    if (rowsAffected > 0) {
                        System.out.println("Thêm khách hàng thành công!");
                        updateTable();
                    } else {
                        System.out.println("Thêm khách hàng thất bại!");
                    }
                } catch (SQLException ex) {
                    System.err.println("Lỗi thực hiện truy vấn thêm: " + ex.getMessage());
                }
            }
        } catch (SQLException ex) {
            System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
        }
        clearInputFields();
    }//GEN-LAST:event_btnAddkhActionPerformed

    private void btnLuukhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuukhActionPerformed
        int selectedRowIndex = tbkhachhang.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Get the values from the input fields
            String idkh = txtMaKhachHang.getText();
            String tenkh = txtHoTen.getText();
            String gioitinhkh = (String) cboGioiTinh.getSelectedItem();
            String ngaysinhkh = txtNgaySinh.getText();
            String cccd = txtCCCD.getText();
            String diachi = txtDiaChi.getText();
            String sdt = txtDienThoai.getText();
            String quoctich = txtQuocTich.getText(); // Assuming you have a JComboBox for roomid

            try (Connection connection = getConnect()) {
                // Kiểm tra nếu kết nối thành công
                if (connection != null) {
                    // Chuẩn bị câu truy vấn SQL để cập nhật thông tin khách hàng
                    String query = "UPDATE khach_hang SET ten = ?, Ngaysinh = ?, gioi_tinh = ?, dia_chi = ?, quoc_tich = ?, CCCD = ?, dien_thoai = ? WHERE id = ?";

                    try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                        // Thiết lập giá trị cho các tham số trong câu truy vấn

                        preparedStatement.setString(1, tenkh);
                        preparedStatement.setString(2, ngaysinhkh);
                        preparedStatement.setString(3, gioitinhkh);
                        preparedStatement.setString(4, diachi);
                        preparedStatement.setString(5, quoctich);
                        preparedStatement.setString(6, cccd);
                        preparedStatement.setString(7, sdt);
                        preparedStatement.setString(8, idkh);

                        // Thực hiện truy vấn cập nhật
                        int rowsAffected = preparedStatement.executeUpdate();

                        if (rowsAffected > 0) {
                            System.out.println("Cập nhật thông tin khách hàng thành công!");
                            // Sau khi cập nhật thành công, cập nhật lại bảng
                            updateTableKhachHang();
                            // Xóa nội dung trong các trường nhập liệu sau khi lưu
                            clearInputFields();
                        } else {
                            System.out.println("Không tìm thấy khách hàng để cập nhật!");
                        }
                    } catch (SQLException ex) {
                        System.err.println("Lỗi thực hiện truy vấn cập nhật: " + ex.getMessage());
                    }
                }
            } catch (SQLException ex) {
                System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
            }
        } else {
            System.out.println("Vui lòng chọn một dòng để cập nhật!");
        }
    }//GEN-LAST:event_btnLuukhActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtQuocTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuocTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuocTichActionPerformed

    private void cboGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGioiTinhActionPerformed

    private void btnXoakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoakhActionPerformed
        int selectedRowIndex = tbkhachhang.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Lấy giá trị của cột CID từ dòng được chọn
            String idkh = tbkhachhang.getValueAt(selectedRowIndex, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection connection = getConnect()) {
                    // Kiểm tra nếu kết nối thành công
                    if (connection != null) {
                        // Chuẩn bị câu truy vấn SQL để xóa thông tin khách hàng
                        String query = "DELETE FROM khach_hang WHERE id = ?";

                        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                            // Thiết lập giá trị cho tham số trong câu truy vấn
                            preparedStatement.setString(1, idkh);

                            // Thực hiện truy vấn xóa
                            int rowsAffected = preparedStatement.executeUpdate();

                            if (rowsAffected > 0) {
                                System.out.println("Xóa thông tin khách hàng thành công!");
                                // Sau khi xóa thành công, cập nhật lại bảng
                                updateTableKhachHang();
                                // Xóa nội dung trong các trường nhập liệu sau khi xóa
                                clearInputFields();
                            } else {
                                System.out.println("Không tìm thấy khách hàng để xóa!");
                            }
                        } catch (SQLException ex) {
                            System.err.println("Lỗi thực hiện truy vấn xóa: " + ex.getMessage());
                        }
                    }
                } catch (SQLException ex) {
                    System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
                }
            }
        } else {
            System.out.println("Vui lòng chọn một dòng để xóa!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoakhActionPerformed
    
    
    public void updateTableKhachHang() {
    try (Connection connection = getConnect()) {
        // Kiểm tra nếu kết nối thành công
        if (connection != null) {
            // Chuẩn bị câu truy vấn SQL để lấy dữ liệu từ bảng khachhang
            String query = "SELECT * FROM khach_hang";

            try (PreparedStatement preparedStatement = connection.prepareStatement(query);
                 ResultSet resultSet = preparedStatement.executeQuery()) {

                // Xóa dữ liệu hiện tại trong bảng
                DefaultTableModel model = (DefaultTableModel) tbkhachhang.getModel();
                model.setRowCount(0);

                // Duyệt qua kết quả và thêm vào bảng
                while (resultSet.next()) {
                    String idkh  = resultSet.getString("id");
                    String tenkh = resultSet.getString("ten");
                    String ngaysinhkh = resultSet.getString("Ngaysinh");
                    String gioitinh = resultSet.getString("gioi_tinh");
                    String diachi = resultSet.getString("dia_chi");
                    String quoctich = resultSet.getString("quoc_tich");
                    String cccd = resultSet.getString("CCCD");
                    String sdt = resultSet.getString("dien_thoai");

                    model.addRow(new Object[]{idkh, tenkh, ngaysinhkh, gioitinh, diachi, quoctich, cccd, sdt});
                }
            } catch (SQLException ex) {
                System.err.println("Lỗi thực hiện truy vấn: " + ex.getMessage());
            }
        }
    } catch (SQLException ex) {
        System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
    }
}
    
    public void updateTable() {
        try (Connection connection = getConnect()) {
//         Kiểm tra nếu kết nối thành công
            if (connection != null) {
            // Chuẩn bị câu truy vấn SQL để lấy dữ liệu từ bảng khachhang
                String query = "SELECT * FROM khach_hang";

                try (PreparedStatement preparedStatement = connection.prepareStatement(query);
                     ResultSet resultSet = preparedStatement.executeQuery()) {

                // Xóa dữ liệu hiện tại trong bảng
                    DefaultTableModel model = (DefaultTableModel) tbkhachhang.getModel();
                    model.setRowCount(0);

                // Duyệt qua kết quả và thêm vào bảng
                    while (resultSet.next()) {
                        String idkh  = resultSet.getString("id");
                        String tenkh = resultSet.getString("ten");
                        String ngaysinhkh = resultSet.getString("Ngaysinh");
                        String gioitinh = resultSet.getString("gioi_tinh");
                        String diachi = resultSet.getString("dia_chi");
                        String quoctich = resultSet.getString("quoc_tich");
                        String cccd = resultSet.getString("CCCD");
                        String sdt = resultSet.getString("dien_thoai");

                        model.addRow(new Object[]{idkh, tenkh, ngaysinhkh, gioitinh, diachi, quoctich, cccd, sdt});
                    }
            }   catch (SQLException ex) {
                    System.err.println("Lỗi thực hiện truy vấn: " + ex.getMessage());
            }
        }
    } catch (SQLException ex) {
        System.err.println("Lỗi kết nối đến cơ sở dữ liệu: " + ex.getMessage());
    }
    }    
    
    private void clearInputFields() {
    // Xóa nội dung trong các trường nhập liệu
txtMaKhachHang.setText("");
txtHoTen.setText("");
cboGioiTinh.setSelectedIndex(0);
txtNgaySinh.setText("");
txtCCCD.setText("");
txtDiaChi.setText("");
txtDienThoai.setText("");
txtQuocTich.setText("");
    
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddkh;
    private javax.swing.JButton btnLuukh;
    private javax.swing.JButton btnSuakh;
    private javax.swing.JButton btnXoakh;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkhachhang;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQuocTich;
    // End of variables declaration//GEN-END:variables
}
